version: '3.8'

services:
  nextjs-app:
    build:
      context: ./nextjs-app
    container_name: nextjs-app
    environment:
      MONGODB_URI: "mongodb+srv://simonhastrupjensen:TvrLm9gVK7ahWEPt@cluster0.e3e1e.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - "3000:3000"
    restart: always

  mqtt-sub:
    build:
      context: ./mqtt-service
    container_name: mqtt-service
    environment:
      MQTT_USER: "grp2"
      MQTT_PASS: "ElskerOgKode321"
      MQTT_PORT: 9001
      API_URL: "http://79.171.148.142:3000/"
      MONGODB_URI: "mongodb+srv://simonhastrupjensen:TvrLm9gVK7ahWEPt@cluster0.e3e1e.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - "9001:9001"
    restart: always
