version: '3.8'

services:
  nextjs-app:
    build:
      context: ./nextjs-app
    container_name: nextjs-app
    environment:
      MONGODB_URI: "mongodb+srv://simonhastrupjensen:TvrLm9gVK7ahWEPt@cluster0.e3e1e.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0"
    ports:
      - "3000:3000"
    restart: always

  mqtt-sub:
    build:
      context: ./mqtt-sub
    container_name: mqtt-sub
    environment:
      MQTT_USER: "grp2"
      MQTT_PASS: "ElskerOgKode321"
      MQTT_IP: "ws://127.0.0.1:9001"
      API_URL: "http://nextjs-app:3000/"
      MONGODB_URI: "mongodb+srv://simonhastrupjensen:TvrLm9gVK7ahWEPt@cluster0.e3e1e.mongodb.net/Cluster0?retryWrites=true&w=majority&appName=Cluster0"
    restart: always
